version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_with_vector
    environment:
      - POSTGRES_DB=my_project_db
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_secret_password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: