version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_with_vector
    environment:
      - POSTGRES_DB=frodo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=72uQSxPWE5AsRt1KTMIj
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


    services:
      api:
        # ... ваші налаштування
        networks:
          - my-shared-network

    networks:
      my-shared-network:
        external: true
